### ISSUE TITLE
files missing

### ISSUE THREAD

**Issue by jdomke** [LLNL/benchpark#10]
```
./bin/benchpark
Missing arguments. Run rambler.sh   
```

```
find . -name rambler.sh
<nothing>
```

**Comment by becker33** [comment]
you need to run 

`./bin/benchpark $experiment $system $directory`

E.g. 

`./bin/benchpark saxpy/openmp cts1 /path/to/setup/workspace`

And we need to change the README not to reference the old name.

**Comment by jdomke** [comment]
yes, but that is inconsistent with what is written in the paper

**Comment by alecbcs** [comment]
@jdomke thanks for point this out. We've gone ahead and updated the paper. I'll submit a PR to clean up the documentation  in the repository as well.
