### ISSUE TITLE
Object 'saxpy' not found in repository

### ISSUE THREAD

**Issue by SBA0486** [LLNL/benchpark#120]
I am trying to run saxpy on an X86 node with setup saxpy/openmp nosite-x86_64 following step 1-6 of the documentation, but at step 5 I get the following error : 

> Object 'saxpy' not found in repository '~/benchpark/ramble/var/ramble/repos/builtin'

In step 4, setup.sh is generated with a message to source it to complete the benchpark setup.
But, after doing so, I have this error after moving to `saxpy/openmp/nosite-x86_64/workspace/` and executing `ramble -P -D . workspace setup`.
Am I missing something?

**Comment by rfhaque** [comment]
@SBA0486, 'saxpy' is not a part of Ramble's builtin repo. It is instead located in the Benchpark repo (`repo/saxpy`). Benchpark's repository is added to Ramble during the initial setup
`bin/benchpark setup saxpy/openmp nosite-x86_64 </path/to/experiment>`
If your build uses an existing Ramble clone, the setup script will (incorrectly) skip adding Benchpark repo to Ramble leading to this error.
You can try a fresh build that creates new clones of Spack and Ramble.

The steps would be as follows:
1. `git clone git@github.com:LLNL/benchpark.git`
2. `cd benchpark/bin`
3. `./benchpark setup saxpy/openmp nosite-x86_64 </new/path/to/experiment>`
4. `. </new/path/to/experiment>/setup.sh`
5. `ramble -P -D </new/path/to/experiment>/saxpy/openmp/nosite-x86_64/workspace workspace setup`
