### ISSUE TITLE
issue with open files

### ISSUE THREAD

**Issue by jdomke** [LLNL/benchpark#157]
running `bin/benchpark setup` while packages.yaml is opened in vim results in problems for `ramble -P -D ...`
```
==> Error: 'utf-8' codec can't decode byte 0xb3 in position 17: invalid start byte
```

It seems that some vim temp files are used in the background. When I close the file and run `ramble -P -D ...` again i get a new error pointing to some .swp file from vim:
```
==> Error: [Errno 2] No such file or directory: '/vol0005/mdt3/data/ra000020/u10016/benchpark/test.gnu/amg2023/openmp/RCCS-Fugaku-Fujitsu-A64FX-TofuD/workspace/configs/auxiliary_software_files/.packages.yaml.swp'
```

**Comment by rfhaque** [comment]
@jdomke The `bin/benchmark setup` step creates a symlink to all the config files including `configs/RCCS-Fugaku-Fujitsu-A64FX-TofuD/auxiliary_software_files/.packges.yaml.swp` (which will be present is the packages.yaml is opened in vim). 
If between `bin/benchmark setup` and `ramble -P -D ...`, the vim temp file gets deleted, we get the 
`No such file or directory` error. 
The workaround is to remove the symlink `/vol0005/mdt3/data/ra000020/u10016/benchpark/test.gnu/amg2023/openmp/RCCS-Fugaku-Fujitsu-A64FX-TofuD/workspace/configs/auxiliary_software_files/.packages.yaml.swp`
@pearce8 @scheibelp We should exclude non-config files from symlink creation in `bin/benchmark setup`
