### ISSUE TITLE
we need alternative location to ~/.spack

### ISSUE THREAD

**Issue by jdomke** [LLNL/benchpark#165]
i ran two instances of ramble workspace setup and it broke ~/.spack/bootstrap/config/linux/config.yaml by adding a lonely 6 in the last line:
```
 57   debug: false
 58   build_jobs: 16
 59 6
```
consequently some new exec of workspace setup failed:
```
==> Error: error parsing YAML: near /home/u10016/.spack/bootstrap/config/linux/config.yaml, 58, 0: could not find expected ':'
    while scanning a simple key
  in "/home/u10016/.spack/bootstrap/config/linux/config.yaml", line 59, column 1
could not find expected ':'
  in "/home/u10016/.spack/bootstrap/config/linux/config.yaml", line 60, column 1
```

To fix that, benchpark shouldn't use ~/.spack but something local like ./<workspace>/.spack (or at least try to lock the files before writing to it, but that is less preferred because i would like to have a "clear" ~/.spack folder for other work, which isn't altered by benchpark).

**Comment by scheibelp** [comment]
When you ran 

`benchpark setup <experiment> <config> <workspace-dir>`

did you run

`source <workspace-dir>/setup.sh`

?

if so, then `SPACK_DISABLE_LOCAL_CONFIG` should be set in your shell. If you see that shell variable, but are still getting complaints about `~/.spack`, can you mention that here (and likewise, if this resolves your problem, can you mention that)?

**Comment by jdomke** [comment]
yes, i'm 99% sure i ran `benchpark setup ...` and then `source <workspace-dir>/setup.sh` from two different directories which resulted in the described error (actually from 3 instances, but that shouldn't matter), but can double check tomorrow to see if the env var is set correctly
