### ISSUE TITLE
Add documentation on spack modules

### ISSUE THREAD

**Issue by pearce8** [LLNL/benchpark#177]
Where should this live?
- A sub-bullet under "Adding a Specific System configuration"
- FAQ: I would like to use external dependencies ...  Adding a Specific System could point here.

Explain that if installed software does not have correct rpaths (e.g., it was installed by EasyBuild), it needs to be added as a spack external module, not just a spack external.

Point at Spack modules documentation.

**Comment by becker33** [comment]
https://spack.readthedocs.io/en/latest/packages_yaml.html#external-packages is the correct Spack documentation ref. If you search `modules` in the spack docs you'll get all results about Spack-generated modules which is a different issue.
