### ISSUE TITLE
benchpark list

### ISSUE THREAD

**Issue by pearce8** [LLNL/benchpark#23]
=== Spack has:
spack list
spack list sql   //anything that has sql in the name
spack list --search-description documentation
spack info --all mpich
spack versions libelf //all versions of libelf
spack tags 
spack tags [-hia] [tag ...]  //for a specific tag

=== Ramble has:
ramble list
ramble list [-hd] [--format {name_only,version_json,html}] [--update FILE] [-t TAGS] ...
   //can search the description, and by tags
ramble list wrf   //all versions of wrf application
ramble info application //info on a given application
 
=== Benchpark has at least 2 additional needs:
1.  What system definitions are available?
2. What benchmarks are defined in my repo (not yet upstreamed to Spack and/or Ramble)
 
Notes from discussing with Doug about #1:
 
System definitions in Benchpark are template workspaces, so we could point Ramble at the system directory to grab the names, but this won’t work with hierarchical system definitions (e.g., llnl/cts1, llnl/ats4).
 
We could activate one system and add ramble config to layer an experiment?
 
Doug wants to at some point add functionality to generate a workspace from another workspace
Have a directory of template workspaces
Ramble workspace from a template
Which might enable more options from the above.
 
What about the benchmark definitions for #2?

**Comment by tgamblin** [comment]
testing tagging @scheibelp

**Comment by tgamblin** [comment]
@pearce8 you can add him as a collaborator on just this project FYI
