### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by pearce8** [LLNL/benchpark#35]
Raise an exception if benchpark setup received incorrect parameters (right now the code just returns).

**Comment by slabasan** [comment]
This issue looks resolved, are there other exceptions you'd like to add?

```
$ ./benchpark se
usage: benchpark [-h] {list,setup} ...
benchpark: error: argument subcommand: invalid choice: 'se' (choose from 'list', 'setup')
```

```
$ ./benchpark setup
usage: benchpark setup [-h] benchmark system workspace_root
benchpark setup: error: the following arguments are required: benchmark, system, workspace_root
```

```
$ ./benchpark --help
usage: benchpark [-h] {list,setup} ...

Benchpark

options:
  -h, --help    show this help message and exit

Subcommands:
  {list,setup}
    list        List available benchmarks and systems
    setup       Create a benchmark and prepare it to build/run
```

**Comment by pearce8** [comment]
I think we need to raise an exception instead of returning on line 195 of bin/benchpark:

`    if not (valid_benchmark and valid_system):
        return
` 

@scheibelp, please remind me what you were suggesting to do here?  I think you were saying to inherit from an exception, but I don't recall the details.

**Comment by scheibelp** [comment]
This is referring to https://github.com/LLNL/benchpark/pull/27#discussion_r1373909506: I recommended changing how we handle cases where we cannot proceed.

**Comment by slabasan** [comment]
Reference for exception handling: https://github.com/spack/spack/blob/b8302a8277a2966f6a01c22867301882f309343f/lib/spack/spack/error.py#L16
