### ISSUE TITLE
tqdm required by ramble

### ISSUE THREAD

**Issue by slabasan** [LLNL/benchpark#39]
`==> Error: Module `tqdm` is not found. Ensure requirements.txt are installed.`

Should we be automatically be installing Ramble's package requirements as part of benchpark's setup or let the user get to the setup step of benchpark before hitting this error?

**Comment by pearce8** [comment]
Yes, lets install Ramble's package requirements at benchpark setup, it doesn't make sense to postpone the error.

**Comment by rfhaque** [comment]
@slabasan How do we solve this error?

**Comment by slabasan** [comment]
@rfhaque Let me know what you think of this solution. The benchpark script hides the output, so user doesn't necessarily know these packages are getting installed into their python environment. But it solves the problem of user having the needed packages before running ramble.

**Comment by rfhaque** [comment]
@pearce8 @slabasan This issue can be bypassed by using the --disable-progress-bar option in ramble

**Comment by slabasan** [comment]
Interestingly, ramble requires tqdm if you do a `ramble --help`, but knowing we can bypass the tqdm requirement with this flag seems sufficient. I don't recall seeing the progress bars even if I did have tqdm in my environment, so I think it's reasonable to use this flag instead of installing it for the user.
